### ISSUE TITLE
Exercise 3 Task 2: show trend of malaria cases over time

### ISSUE THREAD

**Issue by ernestguevarra** [OxfordIHTM/rstats-exercises#16]
Plot malaria cases over time and amount of rainfall over time in this administrative district of Ethiopia;

**Comment by ernestguevarra** [comment]
Team @OxfordIHTM/neji, I am assigning Exercise 3 Task 1 (#15) and Task 2 to your team and I want @Bokchol to be lead developer.

You have by the end of this coming weekend (4 February) to either submit a PR for my review or submit a PR for another team to review.

**Comment by Bokchol** [comment]
Noted @ernestguevarra 👍
